\setcounter{section}{3}
\setcounter{subsection}{4}

## Soundness

In this section we prove the soundness of the inference rules with respect to the semantics. This means we ensure that if we can infer the well-typedness of a program, the execution of the program yields those kinds of values predicted by the inference rules.

### Soundness of the Type Signature

The inference rules and the semantics for the type signatures are built in a structurally similar way. Thus, we will now show that the semantics of a phrase yields the kind of result predicted by the inference rules.

```{theorem}
\label{thm:soundness_list-type-fields}
\begin{letIn}
$\Gamma$ be a type context, $\mathit{ltf}\in\mf{<list-type-fields>}$, $a_i\in\mathcal{V}$,$T_i\in\mathcal{T}$ for $i\in\mathbb{N}_1^n$ and $n\in\mathbb{N}_0$. Assume that $\Gamma\vdash \mathit{ltf}:\{a_1:T_1,\dots,a_n:T_n\}$ can be derived.
\end{letIn}
Then \(\semantic{$\mathit{ltf}$}_\Gamma = \{a_1:T_1,\dots,a_n:T_n\}\).
```
```{proof}
Let $\Gamma$ be a type context, $\mathit{ltf}\in\mf{<list-type-fields>}$, $a_i\in\mathcal{V}$,$T_i\in\mathcal{T}$ for $i\in\mathbb{N}_1^n$ and $n\in\mathbb{N}_0$. Assume $\mathit{ltf}:\{a_1:T_1,\dots,a_n:T_n\}$ can be derived.
\begin{itemize}
    \item \textbf{Case} $\mathit{ltf} = \mf{""}$ for $n = 0$: Then $\semantic{ltf} = \{ \}$ and therefore the conclusion holds.
    \item \textbf{Case} $\mathit{ltf} = a_1 \ \mf{":"} \ T_1 \ \mf{","} \ \mathit{ltf}_1$ for $\mathit{ltf}_1\in\mf{<list-type-field>}$:
    Then by the premise of the inference rule for $\mathit{ltf}$ we can assume that $\Gamma\vdash \mathit{ltf}_1:\{a_2:T_2,\dots,a_n:T_n\}$ can be derived and by induction hypothesis \(\semantic{$\mathit{ltf}_1$}_\Gamma=\{a_2:T_2,\dots,a_n:T_n\}\). We can now use the semantics as describe in its definition \(\semantic{$ltf$}=\semantic{$a_1 \ \mf{":"} \ T_1 \ \mf{","} \ \mathit{ltf}_1$}=\{a_1:e_1,\dots,a_n:e_n\}\) for $e_i\in\text{value}_\Gamma(T_i)$ for $i\in\mathbb{N}_0^n$, thus the conclusion \(\semantic{$\mathit{ltf}$}\in\text{value}_\Gamma(\{a_1:T_1,\dots,a_n:T_n\})\) follows.
  \end{itemize}
```

```{theorem}
\label{thm:soundness_list-type}
\begin{letIn}
$\Gamma$ be a type context, $\mathit{lt}\in\mf{<list-type>}, T_i\in\mathcal{T}$ for $i\in\mathbb{N}_1^n$ and $n\in\mathbb{N}_0$. Assume $\Gamma\vdash\mathit{lt}:(T_1,\dots,T_n)$ can be derived.
\end{letIn}
Then \(\semantic{$\mathit{lt}$}_\Gamma=(T_1,\dots,T_n)\).
```
```{proof}
See the combined proof of the conjunction of Theorem \ref{thm:soundness_list-type} and \ref{thm:soundness_type} below.
```

```{theorem}
\label{thm:soundness_type}
\begin{letIn}
$\Gamma$ be a type context, $t \in\mf{<type>}$ and $T\in\mathcal{T}$. Assume $\Gamma\vdash t:T$ can be derived.
\end{letIn}
Then \(\semantic{$t$}_\Gamma = T\).
```
```{proof}
Combined proof of Theorems \ref{thm:soundness_list-type} and \ref{thm:soundness_type}.

We prove the conjunction of Theorem \ref{thm:soundness_list-type} and \ref{thm:soundness_type} by simultaneous induction over the structure of the mutually recursive grammar rules for $\mf{<list-type>}$ and $\mf{<type>}$.

Let $\Gamma$ be a type context, $\mathit{lt}\in\mf{<list-type>}, T_i\in\mathcal{T}$ for $i\in\mathbb{N}_1^n$ and $n\in\mathbb{N}_0$. Assume $\Gamma\vdash\mathit{lt}:(T_1,\dots,T_n)$ can be derived. We show \(\semantic{$\mathit{lt}$}_\Gamma=(T_1,\dots,T_n)\).
\begin{itemize}
  \item \textbf{Case} $\mathit{lt} = \mf{""}$ for $n = 0$: Then \(\semantic{$\mathit{lt}$}=()\) and thus the conclusion holds.
  \item \textbf{Case} $\mathit{lt} = t_1 \ l_1$ for $t_1\in\mf{<type>}$ for $l_1\in\mf{<list-type>}$:
  Then from the premise of the inference rule, we assume that $\Gamma\vdash l_1:(T_2,\dots,T_n)$ and $\Gamma\vdash t_1 : T_1$ hold. The assumption of Theorem \ref{thm:soundness_type}, namely that $\Gamma\vdash t_1 : T_1$ can be derived, now holds. By its induction hypothesis we can therefore conclude that \(\semantic{$t_1$}_\Gamma=T_1\) for $T_1\in\mathcal{T}$. The assumption of Theorem $\ref{thm:soundness_list-type}$, namely $\Gamma\vdash l_1:(T_2,\dots,T_n)$, holds and therefore by the induction hypothesis of Theorem $\ref{thm:soundness_list-type}$ we obtain \(\semantic{$t_1 \ l_1$}=(t_1,t_2,\dots,t_n)\) for \(\semantic{$t_i$}_\Gamma=T_i\) for $t_i\in\mf{<type>}$. Thus the conclusion \(\semantic{$\mathit{lt}$}=(T_1,\dots,T_n)\) holds.
\end{itemize}

Let $\Gamma$ be a type context, $t \in\mf{<type>}$ and $T\in\mathcal{T}$. Assume $\Gamma\vdash t:T$ can be derived. We show \(\semantic{$t$}_\Gamma = T\).
\begin{itemize}
\item\textbf{Case} $t = \mf{"Bool"}$: Then \(\semantic{$t$}_\Gamma=\mathit{Bool}\) and the conclusion holds.
\item\textbf{Case} $t = \mf{"Int"}$: Then by the premise of the inference rule for $\mf{"Int"}$, we can assume that  $\Gamma\vdash t:\mathit{Int}$ can be derived and therefore \(\semantic{$t$}_\Gamma=\mathit{Int}\). We see that the conclusion holds.
\item\textbf{Case} $t = \mf{"List"} \ t_2$, for $t_2\in\mf{<type>}$: By the premise of the inference rule we assume $\Gamma\vdash t_2:T_2$ can be derived and by induction hypothesis \(\semantic{$t_2$}_\Gamma = T_2\) for given $T_2\in\mathcal{T}$. Then \(\semantic{$t$}_\Gamma=[e_1,\dots,e_n]\) for $e_i\in\text{value}_\Gamma(T_2), i\in\mathbb{N}_0^n$ and $n\in\mathbb{N}$. Thus the conclusion holds.
\item\textbf{Case} $t = \mf{"("} \ t_1 \mf{","} t_2 \ \mf{")"}$, for $t_1,t_2\in\mf{<type>}$: By the premise of the inference rule $\Gamma\vdash t_1:T_1$ and $\Gamma\vdash t_2:T_2$ hold for given $T_1,T_2\in\mathcal{T}$. Then by induction hypothesis \(\semantic{$t_1$}_\Gamma = T_1\) and \(\semantic{$t_2$}_\Gamma = T_2\). Thus by the definition of the semantics the conclusion holds analogously to the cases above.
\item\textbf{Case} $t = \mf{"\{"} \ \mathit{ltf} \ \mf{"\}"}$, for $\mathit{ltf}\in\mf{<list-type-field>}$:
  Then by the premise of the inference rule $\Gamma\vdash \mathit{ltf}:\{a_1:T_1,\dots,a_n:T_n\}$ for $a_i\in\mathcal{V}$,$T_i\in\mathcal{T}$,$i\in\mathbb{N}_1^n$ and $n\in\mathbb{N}_0$. Thus by Theorem \ref{thm:soundness_list-type-fields} \(\semantic{$\mathit{ltf}$}_\Gamma = T\) and therefore the conclusion holds  analogously to the cases above.
\item\textbf{Case} $t = t_1 \ \mf{"->"} \ t_2$, for $t_1,t_2\in\mf{<type>}$: By the premise of the inference rule $\Gamma\vdash t_1:T_1$ and $\Gamma\vdash t_2:T_2$ hold for given $T_1,T_2\in\mathcal{T}$. By induction hypothesis \(\semantic{$t_i$}_\Gamma = T_i\) for $i\in\{1,2\}$. Thus by the definition of the semantics the conclusion holds  analogously to the cases above.
\item\textbf{Case} $t = c \ \mathit{lt}$ for $\mathit{lt}\in\mf{<list-type>}$ and $c\in\mf{<upper-var>}$: By the premise of the inference rule we know $(c,T')\in\Gamma$ with $T'\in\mathcal{T}$ and can assume that $\Gamma\vdash \mathit{lt}:(T_0,\dots,T_n)$ can be derived. Therefore the assumption of Theorem \ref{thm:soundness_list-type}, namely that $\Gamma\vdash \mathit{lt}:(T_0,\dots,T_n)$ can be derived, holds and by applying its induction hypothesis, we know \(\semantic{$\mathit{lt}$}_\Gamma=(T_1,\dots,T_n)\) for $T_i\in\mathcal{T}$, $i\in\mathbb{N}^n$ and $n\in\mathbb{N}_0$. Thus by the definition of the semantics the conclusion holds.
\item\textbf{Case} $t = a$ for $a\in\mathcal{V}$: Then by the definition of the semantics the conclusion holds analogously to the cases above.
\end{itemize}
```

### Soundness of the Variable Context

In our previous sections we had two different meanings for $\Delta$. We will now define the relation between the two.

```{definition,name="Similar Variable context"}
\begin{letIn}
$\Gamma,\Delta$ be type contexts and $\Delta'$ a variable context.
\end{letIn}

We say $\Delta'$ is \textit{ similar to } $\Delta$ \textit{ with respect to } $\Gamma$ iff for all $T \in\mathcal{T}$ there exists $T'\in \mathcal{T}$ such that $T'$ is a uniquely quantified poly type of $T$ in $\Delta$ and for all $a \in\mathcal{V}$ the following holds:
  
\[ (a,T) \in \Delta \Rightarrow \exists e \in \text{value}_\Gamma(T'). (a,e) \in \Delta'.\]
```

Types in $\Delta$ are all uniquely quantified. Instead of proving this, we show that the semantic only produces values of uniquely quantified types. This is a weaker statement but strong enough for our purposes.

### Soundness of the Expression Semantics

We can now use the definition of well-formed variable contexts, to prove the soundness of the expression semantics.

```{theorem}
\label{thm:soundness_bool}
\begin{letIn}
$b\in\mf{<bool>}.$
\end{letIn}
 Then \(\semantic{$b$}\in\text{value}_\varnothing(\mathit{Bool})\).
```
```{proof}
Let $b\in\mf{<bool>}.$
\begin{itemize}
\item\textbf{Case} $b = \mf{"True"}$: Then \(\semantic{b} = \mathit{True}\). Thus the conclusion holds.
\item\textbf{Case} $b = \mf{"False"}$: Then \(\semantic{b} = \mathit{False}\). Thus the conclusion holds.
\end{itemize}
```

```{theorem}
\label{thm:soundness_int}
\begin{letIn}
$i\in\mf{<int>}$.
\end{letIn}
Then \(\semantic{$i$}\in\text{value}_\varnothing(\mathit{Int})\).
```
```{proof}
Let $i\in\mf{<int>}.$
\begin{itemize}
\item\textbf{Case} $i = \mf{"0"}$: Then \(\semantic{i} = 0\). Thus the conclusion holds.
\item\textbf{Case} $i = n$ for $n \in\mathbb{N}$: Then \(\semantic{i} = \mathit{Succ}^n \ 0\). Thus the conclusion holds.
\item\textbf{Case} $i = \mf{"-"} \ n$ for $n \in\mathbb{N}$: Then \(\semantic{i} = \mathit{Neg} \ \mathit{Succ}^n \ 0\). Thus the conclusion holds.
\end{itemize}
```

```{theorem}
\label{thm:soundness_list-exp-field}
\begin{letIn}
$\Gamma$,$\Delta$ be type contexts, $\Delta'$ be a variable context similar to $\Delta$ with respect to $\Gamma$ and $\mathit{lef}\in\mf{<list-exp-field>}$.
Assume $\Gamma,\Delta\vdash\mathit{lef}:T$ can be derived for $T=\{a_1:T_1,\dots,a_n:T_n\}\in\mathcal{T}$, $a_i\in\mathcal{V},T_i\in\mathcal{T}$, for all $i\in\mathbb{N}_1^n$, and $n\in\mathbb{N}_0$. Let $T'\in\mathcal{T}$ be a unique quantified poly type of $T$ in $\Delta$.
\end{letIn}
Then \(\semantic{$\mathit{lef}$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T')\).
```
```{proof}
See the combined proof of the conjunction of Theorem \ref{thm:soundness_list-exp-field}, \ref{thm:soundness_list-exp} and \ref{thm:soundness_exp} below.
```

```{theorem}
\label{thm:soundness_list-exp}
\begin{letIn}
$\Gamma,\Delta$ be type contexts, $\Delta'$ be a variable context similar to $\Delta$ with respect to $\Gamma$ and $\mathit{le}\in\mf{<list-exp>}$. Assume $\Gamma,\Delta\vdash\mathit{le}:\mathit{List} \ T$ can be derived for $T\in\mathcal{T}$. Let $T'\in\mathcal{T}$ be a unique quantified poly type of $\mathit{List} \ T$ in $\Delta$.
\end{letIn}
Then \(\semantic{$\mathit{le}$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T')\).
```
```{proof}
See the combined proof of the conjunction of Theorem \ref{thm:soundness_list-exp-field}, \ref{thm:soundness_list-exp} and \ref{thm:soundness_exp} below.
```

```{theorem}
\label{thm:soundness_exp}
\begin{letIn}
$\Gamma,\Delta$ be type contexts, $\Delta'$ be a variable context similar to $\Delta$ with respect to $\Gamma$. Let $e\in\mf{<exp>}$ and $T\in\mathcal{T}$. Assume $\Delta,\Gamma\vdash e:T$ can be derived. Let $T'\in\mathcal{T}$ be a unique quantified poly type of $T$ in $\Delta$.
\end{letIn}
Then \(\semantic{$e$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T')\).
```
```{proof}
We prove the conjunction of Theorem $\ref{thm:soundness_list-exp-field}$, $\ref{thm:soundness_list-exp}$ and $\ref{thm:soundness_exp}$ by simultaneous induction over the structure of the mutually recursive grammar rules for $\mf{<list-exp-field>},\mf{<list-exp>}$ and $\mf{<exp>}$.

Let $\Gamma$,$\Delta$ be type contexts, $\Delta'$ be a variable context similar to $\Delta$ with respect to $\Gamma$ and $\mathit{lef}\in\mf{<list-exp-field>}$.
Assume the judgment $\Gamma,\Delta\vdash\mathit{lef}:T$ can be derived for $T=\{a_1:T_1,\dots,a_n:T_n\}\in\mathcal{T}$, $a_i\in\mathcal{V},T_i\in\mathcal{T}$, for all $i\in\mathbb{N}_1^n$ and given $n\in\mathbb{N}_0$. We show  \(\semantic{$\mathit{lef}$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T')\) for be a unique quantified poly type $T'\in\mathcal{T}$ of $T$.
\begin{itemize}
\item\textbf{Case} $\mathit{lef}=a_1 \ \mf{"="} \ e_1$ for $e_1\in\mf{<exp>}$ and $n = 1$: Then by the premise of the inference rule we assume $\Gamma,\Delta\vdash e_1:T_1$ can be derived and therefore the assumption of Theorem \ref{thm:soundness_exp} holds. By applying said theorem we can therefore conclude \(\semantic{$e_1$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T_1')\) for a unique quantified poly type $T_1'\in\mathcal{T}$ of $T_1$. Then \(\semantic{$\mathit{lef}$}_{\Gamma,\Delta'} = \{a_1 = e_1\}\) and therefore the conclusion holds.
\item\textbf{Case} $\mathit{lef}=a_1 \ \mf{"="} \ e_1 \ \mf{","} \ \mathit{lef}_0$ for $e_1\in\mf{<exp>}$ and $\mathit{lef}_0\in\mf{<list-exp-field>}$: Then by the premise of the inference rule we assume $\Gamma,\Delta\vdash \mathit{lef}_0:\{a_2:T_2,\dots,a_n:T_n\}$ and $\Gamma,\Delta\vdash e_1: T_1$ can both be derived. Thus the assumption of Theorem \ref{thm:soundness_exp} holds and by the induction hypothesis of said theorem \(\semantic{$e_1$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T_1')\) for be a unique quantified poly type $T'\in\mathcal{T_1'}$ of $T_1$. By $\Gamma,\Delta\vdash \mathit{lef}_0:T$ the assumption for the induction hypothesis of Theorem \ref{thm:soundness_list-exp-field} holds and therefore by appling the theorem we obtain \(\semantic{$\mathit{lef}_0$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T')\) where $T'\in\mathcal{T}$ is a unique quantified poly type of $\{a_2:T_2,\dots,a_n:T_n\}$. Then \(\semantic{$\mathit{lef}$}_{\Gamma,\Delta'}=\{a_1=e_1,\dots,a_n=e_n\}\) for $e_i\in\text{value}_\Gamma(T_i')$ for unique quantified poly types $T_i'\in\mathcal{T}$ of $T_i$ and thus the conclusion holds.
\end{itemize}

Let $\Gamma,\Delta$ be type contexts, $\Delta'$ be a variable context similar to $\Delta$ with respect to $\Gamma$ and $\mathit{le}\in\mf{<list-exp>}$. Assume $\Gamma,\Delta\vdash\mathit{le}:\mathit{List} \ T$ can be derived for given $T\in\mathcal{T}$. We show \(\semantic{$\mathit{le}$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(\mathit{List} \ T)\).
\begin{itemize}
\item \textbf{Case} $\mathit{le} = \mf{""}$: Then \(\semantic{$\mf{""}$}_{\Gamma,\Delta'}=\mathit{Empty}\) and thus the conclusion holds.
\item \textbf{Case} $\mathit{le} = e "," \ \mathit{le}_1$ for $e\in\mf{<exp>}$ and $\mathit{le}_1\in\mf{<list-exp>}$: Then by the premise of the inference rule we assume $\Gamma,\Delta\vdash e:T$ and $\Gamma,\Delta\vdash \mathit{le}_1:\mathit{List} \ T$ can be derived. The assumption of Theorem \ref{thm:soundness_exp}, namely that $\Gamma,\Delta\vdash e:T$ can be derived, holds and by appling that theorem \(\semantic{$e$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T)\) for a unique quantified poly type $T'\in\mathcal{T}$ of $T$. The assumption of Theorem \ref{thm:soundness_list-exp}, namely that $\Gamma,\Delta\vdash \mathit{le}_1:T$ can be derived, also holds and by appling said theorem we conclude \(\semantic{$\mathit{le}_1$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T'')\)  for a unique quantified poly type $T''\in\mathcal{T}$ of $\mathit{List} \ T$. By using the definition of the semantics \(\semantic{$\mathit{le}$}_{\Gamma,\Delta'} = \mathit{Cons} \ e \ \semantic{$\mathit{le}_1$}_{\Gamma,\Delta'} \) and therefore the conclusion holds.
\end{itemize}

//TODO: proof 3.8
```

### Soundness of the Statement Semantics

Statements are modelled as operations on either the type context or the variable context. We will now show that their semantics conforms to the result of the inference rules.

```{theorem}
\label{thm:soundness_list-statement-var}
\begin{letIn}
$\mathit{lsv}\in\mf{<list-statement-var>}$, $a_i\in\mathbb{N}_1^n$ for $n\in\mathbb{N}_0$. Assume $\mathit{lsv}:(a_1,\dots,a_n)$ can be derived.
\end{letIn}
Then \(\semantic{lsv}\in\mathcal{V}^*\).
```
```{proof}
Let $\mathit{lsv}\in\mf{<list-statement-var>}$, $a_i\in\mathbb{N}_1^n$ for $n\in\mathbb{N}_0$. Assume $\mathit{lsv}:(a_1,\dots,a_n)$ can be derived.
\begin{itemize}
\item \textbf{Case} $\mathit{lsv} = \mf{""}$ and $n=0$: Then \(\semantic{$\mathit{lsv}$} = ()\) and thus the conclusion holds.
\item \textbf{Case} $\mathit{lsv} = a_1 \ \mathit{lsv}_1$ for $\mathit{lsv}_1\in\mf{<list-statement-var>}$: Then by the inference rule of $\mathit{lsv}$, we assume that $\mathit{lsv}_1:(a_2,\dots,a_n)$ can be derived. Then by induction hypothesis \(\semantic{$\mathit{lsv}_1$} = (a_2,\dots,a_n)\), and therefore \(\semantic{$\mathit{lsv}$} = (a_1,\dots,a_n)\). Thus the conclusion holds.
\end{itemize}
```

```{theorem}
\label{thm:soundness_statement}
\begin{letIn}
$\Gamma_1,\Gamma_2,\Delta_1,\Delta_2$ be type contexts and $\Delta_1'$ be a variable context similar to $\Delta_1$ respectively with respect to $\Gamma$. Let $s\in\mf{<statement>}$ and assume $\Gamma_1,\Delta_1,s\vdash\Gamma_2,\Delta_2$ can be derived.
\end{letIn}
Then \(\semantic{$s$}(\Gamma_1,\Delta_1') = (\Gamma_2,\Delta_2')\) for a variable context $\Delta_2'$ similar to $\Delta_2$ with respect to $\Gamma$.
```
```{proof}
Let $\Gamma_1,\Gamma_2,\Delta_1,\Delta_2$ be type contexts and $\Delta_1',\Delta_2'$ be a variable context similar to $\Delta_1,\Delta_2$ respectively with respect to $\Gamma_1,\Delta_2$ respectively. Let $s\in\mf{<statement>}$ and assume $\Gamma_1,\Delta_1,s\vdash\Gamma_2,\Delta_2$ can be derived.
\begin{itemize}
\item \textbf{Case} $s = \mathit{mss} \ a \ \mf{"="} \ e$ for $\mathit{mss}\in\mf{<maybe-statement-sort>}$, $a \in\mathcal{V}$, $e\in\mf{<exp>}$, $\Gamma_1=\Gamma_2$ and $\Delta_2=\text{insert}_{\Delta_1}(\{(a,T)\})$ for $T\in\mathcal{T}$: Then from the premise of the inference rule, we assume that $\Gamma_1,\mathit{mss}\vdash e:T$ and $\Gamma_1,\Delta_2\vdash e:T$ can both be derived. Then by Theorem \ref{thm:soundness_exp}, we know $\semantic{$e$}_{\Gamma_1,\Delta_1'}\in\text{value}_{\Gamma_1}(T')$ for a unique quantified poly type $T'\in\mathcal{T}$ of $T$ in $\Delta_1$. Let \(\Delta_2'=\Delta_1'\cup\{(a,\semantic{$e$}_{\Gamma_1,\Delta_1'})\}\). Then \(\semantic{$s$}(\Gamma_1,\Delta_1')=(\Gamma_2,\Delta_2')\).

We will now show that $\Delta_2'$ is similar to $\Delta_2$. We know $\Delta_1$ is similar to $\Delta_1'$ with respect to $\Gamma$, meaning for all $T_1 \in\mathcal{T}$ there exists a uniquely quantified poly type $T_1'\in \mathcal{T}$ of $T_1$ in $\Delta$ and for all $a \in\mathcal{V}$ the following holds: \( (a,T_1) \in \Delta \Rightarrow \exists e \in \text{value}_\Gamma(T_1'). (a,e) \in \Delta'.\)

Let $\a'\in\mathcal{V}$ and $T_1\in\mathcal{T}$ such that $(a',T_1)\in\Delta_2$. We already know $\Delta_2=\text{insert}_{\Delta_1}\{(a,T)\}=\Delta_1 \cup \{(a,T')\}$ for $T'\in\mathcal{T}$ such that $T'$ is a uniquely quantified poly type of $T$ in $\Delta_2$.
\begin{itemize}
\item \textbf{Case} $(a',T_1)\in\Delta_1$: Because $\Delta_1$ is similar to $\Delta_1'$ we can directly conclude $\exists e \in \text{value}_\Gamma(T_1'). (a,e) \in \Delta_2'$ for a uniquely quantified poly type $T_1'$ of $T_1$ in $\Delta_2$.
\item \textbf{Case} $(a',T_1) = (a,T')$: We know $\semantic{$e$}_{\Gamma_1,\Delta_1'}\in\text{value}_\Gamma(T'')$ for a uniquely quantified poly type $T''$ of $T$ in $\Delta_2$. Let $T_0$ be the mono type of $T$. Then $T''=\forall a_1 \dots\forall a_n.T_0$ and $T'=\forall b_1 \dots\forall b_m.T_0$ for $a_i,b_i\in\mathcal{V}$ and $m,n\in\mathbb{N}$. By the definition of uniquely quanified poly types, we know that $\{a_1,\dots,a_n\}=\text{free}(T)=\{b_1,\dots,b_m\}$. Therefore $n=m$ and furthermore $T'$ and $T''$ only differ in the order the bound variables are quantified. Thus $\text{value}_\Gamma(T'')=\text{value}_\Gamma(T')$ and by that $(a',\semantic{$e$}_{\Gamma_1,\Delta_1'}) \in \Delta_2'$.
\end{itemize}
Thus, the conclusion holds.
\item \textbf{Case} $s = \mf{"type alias"} \ c \ \mathit{lsv} \ \mf{"="} \ t$ for  $\mathit{lsv}\in\mf{<list-statement-variable>}$, $c\in\mathcal{V}$ such that $\Delta_1=\Delta_2$ and $(c,\_)\not\in\Gamma_1$: Let $\Delta_1'=\Delta_2'$. From \(\semantic{$s$}(\Gamma_1,\Delta_1')=(\Gamma_2,\Delta_2')\) the conclusion trivially holds.
\end{itemize}
```

```{theorem}
\label{thm:soundness_list-statement}
\begin{letIn}
$\Gamma_1,\Delta_1,\Gamma_2,\Delta_2$ be type contexts and $\Delta_1',$ be a variable context similar to $\Delta_1$ with respect to $\Gamma$. Let $\mathit{ls}\in\mf{<list-statement>}$ such that $\Gamma_1,\Delta_1,\mathit{ls}\vdash\Gamma_2,\Delta_2$ can be derived.
\end{letIn}
Then \(\semantic{$\mathit{ls}$}(\Gamma_1,\Delta_1') = (\Gamma_2,\Delta_2')\) for a variable context $\Delta_2'$ similar to $\Delta_2$ with respect to $\Gamma$.
```
```{proof}
$\Gamma_1,\Delta_1,\Gamma_2,\Delta_2$ be type contexts and $\Delta_1',$ be a variable context similar to $\Delta_1$ with respect to $\Gamma$. Let $\mathit{ls}\in\mf{<list-statement>}$ such that $\Gamma_1,\Delta_1,\mathit{ls}\vdash\Gamma_2,\Delta_2$ can be derived.

\begin{itemize}
\item \textbf{Case} $\mathit{ls} = \mf{""}$ for $\Gamma_1 =\Gamma_2$ and $\Delta_1=\Delta_2$: Let $\Delta_1'=\Delta_2'$. Then \(\semantic{$\mathit{ls}$}=\mathit{id}\) and therefore the conclusion holds.
\item \textbf{Case} $\mathit{ls} = s \ \mf{";"} \ \mathit{ls}_1$ for $s\in\mf{<statement>}$ and $\mathit{ls}_1\in\mf{<statement-list>}$: From the premise of the inference rule, we assume $\Gamma_1,\Delta_1,s\vdash \Gamma_3,\Delta_3$ and $\Gamma_3,\Delta_3,\mathit{ls}_1\vdash \Gamma_2,\Delta_2$ for some type contexts $\Gamma_2,\Delta_2$. We know by Theorem \ref{thm:soundness_statement} that \(\semantic{$s$}(\Gamma_1,\Delta_1')=(\Gamma_3,\Delta_3')\) for a given variable context $\Delta_3'$ similar to $\Delta_3$ with respect to $\Gamma$. Also, by induction hypothesis we know \(\semantic{$\mathit{ls}_1$}(\Gamma_3,\Delta_3')=(\Gamma_2,\Delta_2')\) for a given $\Delta_2'$ similar to $\Delta_2$ with respect to $\Gamma$. Thus \(\semantic{$\mathit{ls}$}=\semantic{$s$}\circ\semantic{$\mathit{ls}_1$}\) and therefore the conclusion holds.
\end{itemize}

```

### Soundness of the Program Semantic

A program is a sequence of statements. Starting with an empty type context, and an empty variable context, one statement at the time will be applied, resulting in a value $e$, a type $T$ and a type context $\Gamma$ such that $e\in\text{value}_\Gamma(T)$.

```{theorem}
\label{thm:soundness_program}
\begin{letIn}
$p\in\mf{<program>}$ and $T\in\mathcal{T}$. Assume $p:T$ can be derived.
\end{letIn}

Then there exists type contexts $\Gamma$ and $\Delta$ such that \(\semantic{$p$}\in\text{value}_\Gamma(T')\) for a uniquely quantified poly type $T'\in\mathcal{T}$ of $T$ in $\Delta$.
```
```{proof}
Let $\mathit{ls} \ \mathit{mms} \ \mf{"main="} \ e \in\mf{<program>}$, $\mathit{ls}\in\mf{<list-statement>}$, $\mathit{mms}\in\mf{<maybe-main-sign>}$ and $e\in\mf{<exp>}$. Assume $p:T$ for $T\in\mathcal{T}$, $\varnothing,\varnothing,\mathit{ls}\vdash\Gamma,\Delta$ and \(\Gamma,\Delta\vdash e:T\) can be derived for type contexts $\Gamma$ and $\Delta$.

The assumption of Theorem \ref{thm:soundness_list-statement}, namely that $\varnothing,\varnothing,\mathit{ls}\vdash\Gamma,\Delta$ can be derived, holds. By appling said theorem we obtain \(\semantic{$\mathit{ls}$}(\varnothing,\varnothing)=(\Gamma,\Delta')\) for a variable context $\Delta'$ similar to $\Delta$ with respect to $\Gamma$. Therefore, \(\semantic{$p$} = \semantic{$e$}_{\Gamma,\Delta'}\). We know $\Gamma,\Delta\vdash e:T$ and thus by Theorem \ref{thm:soundness_exp} we now that \(\semantic{$e$}_{\Gamma,\Delta'}\in\text{value}_\Gamma(T')\) for a uniquely quantified poly type $T'\in\mathcal{T}$ of $T$ in $\Delta$ and therefore the conclusion holds.
```
