### Inference Rules for type signatures

#### list-lower-var
Judgment: $llv:(a_1,\dots,a_n)$

\logicRule
{}
{\mf{""}:()}
{}
For an empty list we return the empty tuple.

\logicRule
{llv:(a_1,\dots,a_n)\quad (a_0,a_1,\dots,a_n)=T}
{a_0 \ llv:T}
{}
For a nonempty list, we append the head $a$ to the type $T$ of the tail $l$.

#### list-type-fields

Judgment: $\Gamma\vdash ltf:\{a_1:T_1,\dots,a_n:T_n\}$

\logicRule
{}
{\Gamma\vdash \mf{""}:\{\}}
{}

\logicRule
{\Gamma\vdash t : T_0\quad
\Gamma\vdash ltf : \{a_1:T_1,\dots,a_n:T_n\}\quad
\{a_0:T_0,a_1:T_1,\dots,a_n:T_n\}=T
}
{\Gamma\vdash a_0 \ \mf{":"} \ t \ \mf{","} \ ltf:T}
{}

The type context $\Gamma$ is used in the judgment $\Gamma\vdash t:T_0$ that turns the type signature $t$ into a type $T_0$.

#### list-type

Judgment: $\Gamma\vdash lt:(T_1,\dots,T_n)$

\logicRule
{}
{\Gamma\vdash \mf{""}:()}
{}

\logicRule
{\Gamma\vdash t:T_0\quad
\Gamma\vdash lt:(T_1,\dots,T_n)\quad
(T_0,T_1,\dots,T_n)=T
}
{\Gamma\vdash t \ lt:T}
{}

#### type

Judgment: $\Gamma\vdash t:T$

\logicRule
{}
{\Gamma\vdash \mf{"Bool"}:\mathit{Bool}}
{}

\logicRule
{}
{\Gamma\vdash\mf{"Int"}:\mathit{Int} }
{}

\logicRule
{\Gamma\vdash t:T}
{\Gamma\vdash\mf{"List" t}:\mathit{List} \ T}
{}
The resulting type is a type application $\mathit{List} \ T$ for the type $\mathit{List} = \forall a.\mu C. [ \ ] \ | \mathit{Cons} \ a \ C$.

\logicRule
{\Gamma\vdash t_1:T_1\quad
\Gamma\vdash t_2:T_2
}
{\Gamma\vdash\mf{"("} \ t_1 \ \mf{","} \ t_2 \ \mf{")"}:(T_1,T_2)}
{}

\logicRule
{\Gamma\vdash ltf:T}
{\Gamma\vdash\mf{"\{"} \ ltf \ \mf{"\}"}:T}
{}

\logicRule
{\Gamma\vdash t_1:T_1\quad
\Gamma\vdash t_2:T_2
}
{\Gamma\vdash t_1 \to t_2:T_1 \to T_2}
{}

\logicRule
{(c,T')\in\Gamma\quad
\Gamma\vdash l:(T_1,\dots,T_n)\quad
\overline{T'} \ T_1 \dots T_n = T
}
{\Gamma\vdash c \ l:T}
{}
For a given type $T$ we write the application constructor as $\overline{T}$.

\logicRule
{(a,T)\in\Gamma\quad
T \text{ is a type variable}
}
{\Gamma\vdash a:T}
{}