# Liquid Types for Elm

In this chapter we will specify a version of liquid types for Elm that can be inferred using an arbitrary SMT solver. Section \@ref(notion-of-liquid-types) will formally define liquid types. Section \@ref(liquid-types-for-elm) will extend the type system of Elm with liquid types. This included the syntax, type inference rules and the denotational semantic. Section \@ref(soundness-of-liquid-types) gives a proof that the extended denotational semantic is sound with respect to the extended type inference rules. Section \@ref(formulating-smt-statements) explains how the SMT statements used for the SMT solver can be generated and proves that the provided algorithm is correct.


## Notion of Liquid Types

So-called _refinement types_ exclude values from existing types by using a predicate (in this context also called a _refinement_). The definition of such a refinement can be chosen quite freely, but it is important to note that one will also need to provide an algorithm to validate such refinements. This motivates the use of SMT solvers and refinements tailored to the capabilities of specific solvers. Such a set of refinement types are for example _liquid types_ (**l**og**i**cally **qu**al**i**fie**d** data types).

We start by defining the syntax and semantic of valid refinements.

```{definition,name="Logical Qualifier Expressions"}
We define the set of logical qualifier expressions $\mathcal{Q}$ as follows:

$$
  \begin{aligned}
    \mathit{IntExp} ::= \ & \mathbb{Z}\\
      | \ & \mathit{IntExp} + \mathit{IntExp}\\
      | \ & \mathit{IntExp} \cdot \mathbb{Z}\\
      | \ & \mathcal{V}
  \end{aligned}
$$

$$
  \begin{aligned}
    \mathcal{Q} ::= \ & \mathit{True}\\
      | \ & \mathit{False}\\
      | \ & \mathit{IntExp} < \mathcal{V}\\
      | \ & \mathcal{V} < \mathit{IntExp}\\
      | \ & \mathcal{V} = \mathit{IntExp}\\
      | \ & \mathcal{Q} \land \mathcal{Q}\\
      | \ & \mathcal{Q} \lor \mathcal{Q}\\
      | \ & \neg \mathcal{Q}
  \end{aligned}
$$
```

```{definition, name="Well-Formed Logical Qualifier Expressions"}
\begin{letIn}
$e \in \mathcal{Q}$. Let $\Theta:\mathcal{V}\nrightarrow\mathbb{N}$.
\end{letIn}
We say $e$ is _well formed_ with respect to $\Theta$ iff for all variables $v$ in $e$, $\Theta(v)$ is well-defined, meaning $\exists n\in\mathbb{N}.(v,n)\in\Theta$.
```

```{definition, name="Semantics of Logical Qualifier Expressions"}
We define the semantic of arithmetic expressions $\mathit{IntExp}$ as follows.
$$
\begin{aligned}
\semantic{$.$}_.: \ &\mathit{IntExp}\to(\mathcal{V}\nrightarrow\mathbb{N})\to\mathbb{N}\\
\semantic{$n$}_\Theta =& n\\
\semantic{$i + j$}_\Theta=& \semantic{$i$}_\Theta + \semantic{$j$}_\Theta\\
\semantic{$i \cdot n$}_\Theta=& \semantic{$i$}_\Theta \cdot n\\
\semantic{$a$}_\Theta=& \Theta(a)\\
\end{aligned}
$$
  
Note that we assume that the given expression is well-formed with respect to&nbsp;$\Theta$.

We also define the semantic of logical qualifier expressions $\mathcal{Q}$ as follows:

$$
\begin{aligned}
\semantic{$.$}_.:\ &\mathcal{Q}\to(\mathcal{V}\nrightarrow\mathbb{N})\to\mathit{Bool}\\
\semantic{$\mathit{True}$}_\Theta =&\mathit{True}\\
\semantic{$\mathit{False}$}_\Theta =& \mathit{False}\\
\semantic{$i < a$}_\Theta =& (\semantic{$i$}_\Theta < \semantic{$a$}_\Theta)\\
\semantic{$a < i$}_\Theta =& (\semantic{$a$}_\Theta < \semantic{$i$}_\Theta)\\
\semantic{$a = i$}_\Theta =& (\semantic{$a$}_\Theta = \semantic{$i$}_\Theta)\\
\semantic{$p \land q$}_\Theta =& (\semantic{$p$}_\Theta \land \semantic{$q$}_\Theta)\\
\semantic{$p \lor q$}_\Theta =& (\semantic{$p$}_\Theta \lor \semantic{$q$}_\Theta)\\
\semantic{$\neg p$}_\Theta =& (\neg \semantic{$p$}_\Theta)
\end{aligned}
$$
```

We will now extend our previous definition of types (see Definition \ref{thm:types}) by the notion of refinement types. This extension is not very interesting, as refinement types don't behave differently from their underlying type.

```{definition,name="Extended Types"}
 We define the following

$T$ is a _mono type_ $:\Leftrightarrow$
$$
\begin{aligned}
         & T \text{ is a type variable}\\
  \lor \ & T \text{ is a type application}\\
  \lor \ & T \text{ is a algebraic type}\\
  \lor \ & T \text{ is a product type}\\
  \lor \ & T \text{ is a function type}\\
  \lor \ & T \text{ is a liquid type }
\end{aligned}
$$
$T$ is a _poly type_ $:\Leftrightarrow$
$$
\begin{aligned}
         & T = \forall a.T'\\
         & \text{where } T' \text{ is a mono type}\\
         & \text{or poly type and } a \text{ is a symbol.}
\end{aligned}
$$
$T$ is a _type_$:\Leftrightarrow$
$$
\begin{aligned}
       \ & T \text{ is a mono type}\\
  \lor \ & T \text{ is a poly type}.
\end{aligned}
$$  
by using the  predicates:
$$
\begin{aligned}
T \text{ is a } \mathit{type} \ \mathit{variable}:\Leftrightarrow \
         & T\in\mathcal{V}\\
T \text{ is a } \mathit{type} \ \mathit{application}:\Leftrightarrow \
         & T \text{ is of form } C \ T_1 \dots T_n\\
         & \text{where } n\in\mathbb{N}, C\in\mathcal{V} \text{ and the } T_i \text{ are mono types for}\\
         & \text{all } i\in\mathbb{N}_1^n.\\
T \text{ is a } \mathit{algebraic} \ \mathit{type}:\Leftrightarrow \
         & T \text{ is of form }\\
         & \mu C. C_1 \ T_{1,1} \dots T_{1,k_1} \ | \dots | \ C_n \ T_{n,1} \dots T_{n,k_n}\\
         & \text{such that }\exists i\in\mathbb{N}.\forall j\in\mathbb{N}_1^{k_i}.T_{i,j}\neq C\\
         & \text{where } n\in\mathbb{N}, C\in\mathcal{V} , k_i\in\mathbb{N}_0 \text{ for all } i\in\mathbb{N}_1^n \\
         & \text{and } \ T_{i,k_i} \text{ is a mono type or } T_{i,k_i} = C \text{ for all } i\in\mathbb{N}_1^n\\
         & \text{and } j\in\mathbb{N}_1^{k_i}.\\
T \text{ is a } \mathit{product} \ \mathit{type}:\Leftrightarrow \
         & T \text{ is of form } \{l_1:T_1,\dots,l_n:T_n\}\\
         & \text{where }n\in\mathbb{N}_0\text{ and } l_i\in\mathcal{V} \text{ and } T_i \text{ are mono types for}\\
         & \text{all } i\in\mathbb{N}_1^n.\\
T \text{ is a } \mathit{function} \ \mathit{type}:\Leftrightarrow \
         & T \text{ is of form } T_1 \to T_2\\
         & \text{where } T_1 \text{ and } T_2 \text{ are mono types}.\\
T \text{ is a }\mathit{liquid} \ \mathit{type} \ :\Leftrightarrow \ 
         & T \text{ is of form } \{ a :\mathit{Int} \ | \ r \}\\
         & \text{where } \ a \in\mathcal{V}, r\in \mathcal{Q},\mathit{Nat}:=\mu C. 1 \ | \ \mathit{Succ} \ C\\
&\text{and }\mathit{Int}:=\mu \_. 0 \ | \ \mathit{Pos} \ Nat \ | \ \mathit{Neg} \ \mathit{Nat}.\\
  \lor \ & T \text{ is of form } a:\{ b :\mathit{Int} \ | \ r \}\to T_0\\
         & \text{where } a,b \in\mathcal{V}, r\in \mathcal{Q}, \text{ and } T_0\ \text{ is a liquid type.}\\
\end{aligned}
$$
```

We will also need to redefine the definition of free variables and type substitution. The only change is the trival addition of refinement types.

```{definition,name="Bound, Free, Set of free variables"}
\begin{letIn}
$a$ be a type variable and
$T$ be a type
\end{letIn}

We say

* $a$ is _free_ in $T :\Leftrightarrow a \in \mathit{free}(T)$
* $a$ is _bound_ in $T :\Leftrightarrow a \not\in \mathit{free}(T)$ and $a$ occurs in $T$.

where

$$
\begin{aligned}
   \mathrm{free}(a) :=& \{a\}\\
   \mathrm{free}(C \ T_1 \dots T_n) :=& \bigcup_{i\in\mathbb{N}_1^n}\mathrm{free}(T_i)\\
   \mathrm{free}\begin{pmatrix*}[l]
    \mu C.\\
    C_1 \ T_{1,1} \dots \ T_{1,k(1)}\\
    | \dots \\
    | \ C_n \ T_{n,1} \dots \ T_{n,k(n)}
    \end{pmatrix*} :=& \bigcup_{i\in\mathbb{N}_0^n}\bigcup_{j\in\mathbb{N}_0^{k_i}}
      \begin{cases}
        \varnothing& \text{ if } T_{i,j} = C\\
        \mathrm{free}(T_{i,j})& \text{ else}
      \end{cases}\\
    \mathrm{free}(\{\_:T_1,\dots,\_:T_n\}) :=&\bigcup_{i\in\mathbb{N}_1^n}\mathrm{free}(T_i)\\
    \mathrm{free}(T_1 \to T_2) :=& \mathrm{free}(T_1)\cup\mathrm{free}(T_2)\\
    \mathrm{free}(\forall a.T) :=& \mathrm{free}(T)\backslash\{a\}\\
    \mathrm{free}(\{a :\mathit{Int} \ | \ r \}) :=& \{\}\\
    \mathrm{free}(a:\{b :\mathit{Int} \ | \ r \}\to T) :=& \{\}
\end{aligned}
$$
  
```

We will now redefine the notion of values. As mentioned before, liquid types exclude values that do not ensure a specific refinement. 

```{definition,name="Values"}
\begin{letIn}
$\mathcal{S}$ be the class of all finite sets and $\Gamma$ be a type context.
\end{letIn}

We define
$$
\begin{aligned}
\mathrm{values}_\Gamma :& \ \mathcal{V} \to \mathcal{S}\\
\mathrm{values}_\Gamma(a) :=& \mathrm{values}_\Gamma(\Gamma(a))\\
\mathrm{values}_\Gamma(C \ T_1 \ \dots \ T_n) :=& \mathrm{values}_\Gamma(\overline{\Gamma(C)}(T_1,\dots,T_n))\\
\mathrm{values}_\Gamma\small\begin{pmatrix*}[l]
    \mu C.\\
    | \ C_1 \ T_{1,1} \dots \ T_{1,k_1}\\
    | \dots \\
    | \ C_n \ T_{n,1} \dots \ T_{n,k_n}
    \end{pmatrix*} :=&\bigcup_{i\in\mathbb{N}_0} \mathrm{rvalues}_\Gamma
  \begin{pmatrix*}[l]
  i,&
  \small\begin{matrix*}[l]
    \mu C.\\
    | \ C_1 \ T_{1,1} \dots \ T_{1,k_1}\\
    | \dots \\
    | \ C_n \ T_{n,1} \dots \ T_{n,k_n}
  \end{matrix*}
  \end{pmatrix*}\\
\small{\mathrm{values}_\Gamma(\{l_1:T_1,\dots,l_n:T_n\})} :=&\Big\{\small{\{l_1=t_1,\dots,l_n=t_n\}} \\
  &| \ \small{\forall i\in\mathbb{N}_1^n.t_i \in\mathrm{values}_\Gamma(T_i)}\Big\}\\
\mathrm{values}_\Gamma(T_1 \to T_2) :=&\{f \ | \ f:\mathrm{values}_\Gamma(T_1)\to\mathrm{values}_\Gamma(T_2)\}\\
\mathrm{values}_\Gamma(\forall a.T) :=& \lambda b.\mathrm{values}_{\{(a,b)\}\cup\Gamma}(T) \text{ where the symbol } b \text{ does}\\
  &\text{not occur in } T.\\
\mathrm{values}_\Gamma(\{ a:\mathit{Int} \ | \ r \}) :=& \mathrm{refinedValues}_{\{\}}(\{ a:\mathit{Int} \ | \ r \})\\
\mathrm{values}_\Gamma(a:\{ b:\mathit{Int} \ | \ r \}\to T) :=& \mathrm{refinedValues}_{\{\}}(a:\{ b:\mathit{Int} \ | \ r \}\to T)
\end{aligned}
$$
using the following helper functions.
  
Let $l\in\mathbb{N},T := \mu C.\ | \ C_1 \ T_{1,1} \dots \ T_{1,k(1)}\ | \dots \ | \ C_n \ T_{n,1} \dots \ T_{n,k(n)}$. We define:
$$
\begin{aligned}
\mathrm{rvalues}_\Gamma(0,T):=&
  \begin{Bmatrix*}[l]
    \begin{array}{l|l}
      C_i \ v_1 \dots v_n
      & \begin{matrix*}[l]
        i\in\mathbb{N}_1^n\\
        \land \forall j\in\mathbb{N}_1^{k(i)}. T_{i,j} \neq C \land v_j \in \mathrm{values}_\Gamma(T_{i,j})
        \end{matrix*}
    \end{array}
  \end{Bmatrix*}\\
\mathrm{rvalues}_\Gamma({l+1},T):=&
  \small\begin{Bmatrix*}[l]
    \begin{array}{l|l}
      C_i \ v_1 \dots v_n
      & \begin{matrix*}[l]
        i\in\mathbb{N}_1^n\\
        \land \forall j\in\mathbb{N}_1^{k(i)}. v_j \in
        \begin{cases}
          \mathrm{rvalues}_\Gamma(l,T)&\text{if } T_{i,j} = C\\
          \mathrm{values}_\Gamma(T_{i,j})&\text{else}
        \end{cases}
        \end{matrix*}
    \end{array}
  \end{Bmatrix*}
\end{aligned} 
$$
Let $\Theta:\mathcal{V}\nrightarrow\mathbb{N}$. We define:
$$
\begin{aligned}
\mathrm{refinedValues}_{\Theta}&(\{ a:\mathit{Int} \ | \ r \}) :=\\
   & \{ n\in \mathrm{values}_{\{\}}(\mathit{Int}) \\
  &| \ r \text{ is well formed with respect to }\Theta\cup\{(a,n)\}\land \ \semantic{$r$}_{\Theta\cup\{(a,n)\}} \}\\
\end{aligned}
$$
$$
\begin{aligned}
\mathrm{refinedValues}_{\Theta}&(a:\{ b:\mathit{Int} \ | \ r \}\to T) :=\\
   &\{b\in \mathrm{refinedValues}_{\Theta}(\{ b:\mathit{Int} \ | \ r \} \to T)\\
 &| \ \forall n\in \mathrm{refinedValues}_{\Theta}(\{ b:\mathit{Int} \ | \ r \}).\\
     &\quad b(n) \in \mathrm{refinedValues}_{\Theta\cup\{(a,n)\}}(T)\}
\end{aligned}
$$
```