# Conclusions

In this thesis, we have investigated the type system for the Elm language and discussed its extension by refinement types.

The original intent was to have an implementation of the type checker for liquid types. We expected that the resulting liquid types are defined such that non-negative integers, range types and non-zero integers can be defined. We expected to implement liquid types for `Int`, `Bool` and tuples of liquid types. Additionally, we expected that the inferred type of the `max` function can be sharp. Such a sharp refinement is $(a \leq \nu) \land (b \leq \nu)\land (\nu = b \lor \nu = a)$.

Indeed, the resulting type system is capable of defining all described integer types and also allows inferring liquid types for functions over integers. However, It does not include liquid types over `Bool` and tuples. Additionally, the inferred type of the max function is not sharp: $(a \leq \nu) \land (b \leq \nu)$. Adding these missing features would have been too time-consuming and would not provide any new revelations:

* The inclusion of Booleans would have meant that we would have needed to type check the liquid expressions. This would have added unnecessary complexity, as we are mainly interested in subtypes of integers.
* Tuples would have been easy to add but would not yield additional behaviour, as Tuples as arguments can be flattened and then transformed into a list of arguments  and Tuples as a return argument are syntax sugar for defining multiple functions with the same input values.
* To infer a sharp refinement for the `max` function, one can simply add $\nu = b \lor \nu = a$ to the search space, but that is not very sophisticated. Another way would be to add $P \lor Q$ for a specific set of allowed predicates for $P$ and $Q$. We used our Elm implementation to quickly test this for the definition of $P$ and $Q$ not containing $\lor$. The resulting refinement was sharp but included a lot of trivial  conditions. The search space increased by a factor of four. This factor could be decreased by ensuring that no two predicates are equivalent.

While working on the thesis it became clear that the original expectations did not completely match the possibilities of liquid types. In particular, the expressiveness of liquid types is directly dependent on the initial set of predicates and the allowed expressions in $\mathcal{Q}$. Extending the allowed expressions in $\mathcal{Q}$ requires that the SMT solver can still cope with them. In contrast to our original expectation, the set of predicates $\mathcal{Q}$ allowed in if-branches is a superset of the predicates allowed in refinements. Additionally, the search space for the derived predicates must be finite. This means that no matter how big the space we are considering is, there will always be a predicate in $\mathcal{Q}$ that cannot be found.

There are multiple future topics that can be explored.

* The set of allowed expressions $\mathcal{Q}$ and the search space for the inferred refinements can be extended to sharpen the inferred predicates. At some point, this would also need to include an algorithm to simplify the inferred predicates. Otherwise, the inferred predicates can only be hardly read by humans.
* The current implementation in Elm can be extended to a full type checker by using the Elm-in-Elm compiler [@elmInElm]. This would require some changes to the type checker part of the Elm-in-Elm compiler. The updated checker would need to collect the subtyping conditions while inferring the type (as discussed in Section \@ref(liquid-types-for-elm)). This can not be done by simply traversing the abstract syntax tree. Such an addition would be simple but tedious, as every type inference rule would need to be updated.
* One can try to implement a specific type in Elm without liquid types. Liquid types make a type system incomplete. Therefore, this is a far better solution of implementing a specific type. For the range type, the author of this thesis has actually found another way, namely to implement these types using phantom types (an algebraic type were not all type variables are used) [@elmStaticArray].

Working on this thesis gave insights into the inner workings of liquid types. It showcased its strengths but also its weaknesses. Liquid types are an interesting topic but are not really a good fit for the Elm language and the philosophies behind it.
\newpage

# (APPENDIX) Appendix {-}

# Source Code

The source code discussed in this thesis can be found under

https://github.com/orasund/elm-refine.
