### Inference Rules for Statements

#### list-statement-var

Judgment: $\mathit{lsv}:(a_1,\dots,a_n)$

\logicRule
{}
{\mf{""}:()}
{}

\logicRule
{\mathit{lsv}:(a_1,\dots,a_n)}
{a_0 \ \mathit{lsv}:(a_0,a_1,\dots,a_n)}
{}

#### list-statement-sort

Judgment: $\mathit{lss}:(c_1:(T_{1,1}, \dots,T_{1,k_1}),\dots,c_n:(T_{n,1}, \dots,T_{n,k_n}))$

\logicRule
{\Gamma\vdash \mathit{lt}:(T_0,\dots,T_n)
}
{c \ \mathit{lt}:(c:(T_0,\dots,T_n))}
{}

\logicRule
{\begin{gathered}
\Gamma\vdash \mathit{lt}:(T_{0,1},\dots,T_{0,k_n})\quad
\mathit{lss}:\begin{pmatrix*}[l]
a_1:(T_{1,1}, \dots,T_{1,k_1}),\\
\vdots\\
a_n:(T_{n,1}, \dots,T_{n,k_n})
\end{pmatrix*}
\end{gathered}
}
{c \ \mathit{lt} \ \mf{"|"} \ lss:\begin{pmatrix*}[l]
a_0:(T_{0,1}, \dots,T_{0,k_0}),\\
a_1:(T_{1,1}, \dots,T_{1,k_1}),\\
\vdots\\
a_n:(T_{n,1}, \dots,T_{n,k_n})
\end{pmatrix*}
}
{}

#### list-statement

Judgment: $\Gamma_1,\Delta_1,\mathit{ls}\vdash \Gamma_2,\Delta_2$

\logicRule
{\Gamma_1=\Gamma_2\quad
\Delta_1=\Delta_2
}
{\Gamma_1,\Delta_1\mf{""}\vdash \Gamma_2,\Delta_2}
{}

\logicRule
{\Gamma_1,\Delta_1,s\vdash \Gamma_2,\Delta_2\quad
\Gamma_2,\Delta_2, \mathit{ls} \vdash \Gamma_3,\Delta_3
}
{\Gamma_1,\Delta_1, s \ \mf{";"} \ \mathit{ls} \vdash \Gamma_3,\Delta_3}
{}

#### maybe-statement-sign

Judgment: $\Gamma,mss\vdash a:T$

\logicRule
{}
{\Gamma,\mf{""}\vdash a:T}
{}

\logicRule
{\Gamma\vdash t:T
a_1 = a_2}
{\Gamma,a_1 \ \mf{":"} \ t \ \mf{";"}\vdash a_2:T}
{}

#### statement

Judgment: $\Gamma_1,\Delta_1,s\vdash \Gamma_2,\Delta_2$

\logicRule
{\begin{gathered}
\Gamma_1 = \Gamma_2\quad
(a,\_)\not\in\Delta_1\\
\Gamma_1,\mathit{mss}\vdash e:T\quad
\Gamma_1,\Delta_1\vdash e : T\quad
\Delta_2 = \Delta_1\cup\{(a,\overline{\Gamma}(T))\}
\end{gathered}
}
{\Gamma_1,\Delta_1, \mathit{mss} \ a \ \mf{"="} e\vdash \Gamma_2,\Delta_2
}
{}

\logicRule
{\begin{gathered}
\Delta_1=\Delta_2\quad
(c,\_)\not\in\Gamma_1\quad
\Gamma\vdash t:T_1\\
T_2 \text{ is a mono type}\quad
\mathit{lsv}:(a_1,\dots,a_n)\quad
\{a_1 \dots a_n \} = \text{free}(T_2)\\
\forall a_1. \dots \forall a_n. T_2 = T_1\quad
\Gamma_2 = \Gamma_2\cup\{(c,T_1)\}
\end{gathered}
}
{\Gamma_1,\Delta_1,\mf{"type alias"} \ c \ \mathit{lsv} \ \mf{"="} \ t \vdash \Gamma_2,\Delta_2
}
{}

\logicRule
{\begin{gathered}
(c,\_)\not\in\Gamma_1\quad
\mathit{lsv}:(a_1,\dots,a_n)\\
\mathit{lss}:(c_1:(T_{1,1}, \dots,T_{1,k_1}),\dots,c_n:(T_{n,1}, \dots,T_{n,k_n}))\\
\Delta_1\cap\{(c_1,\_),\dots,(c_n,\_)\} = \varnothing\quad
\{a_1 \dots a_n \} = \text{free}(T_2)\\
\mu C.c_1 \ T_{1,1} \ \dots \ T_{1,k_1} \ | \ \dots \ | \ c_n \ T_{n,1} \ \dots \ T_{n,k_n}=T_2\quad
\forall a_1. \dots \forall a_n. T_2 = T_1\\
\Gamma_1\cup\{(c,T_1)\} = \Gamma_2\quad
\Delta_1\cup
\begin{Bmatrix*}[l]
(c_1,\overline{\Gamma}(T_{1,1}\to\dots\to T_{1,k_1}\to T_1)),\\
\vdots\\
(c_n,\overline{\Gamma}(T_{n,1}\to\dots\to T_{n,k_n}\to T_1))
\end{Bmatrix*}) = \Delta_2
\end{gathered}
}
{\Gamma_1,\Delta_1,\mf{"type"} \ c \ \mathit{lsv} \mf{"="} \mathit{lss} \vdash\Gamma_2,\Delta_2
}
{}
The list $\mathit{lss}$ provides us with the structure of the type. From there we construct the type $T_2$ and bind all variables, thus creating the poly type $T_1$. Additionally, every sort $c_i$ for $i\in\mathbb{N}_1^n$ has its own constructor that gets added to $\Delta_1$ under the name $c_i$. In Elm these constructors are the only constants beginning with an upper-case letter.

#### maybe-main-sign

Judgment: $\Gamma,\mathit{mms}\vdash \text{main}:T$

\logicRule
{}
{\Gamma,\mf{""}\vdash \text{main}:T}
{}

\logicRule
{\Gamma\vdash t:T}
{\Gamma,\mf{"main :"} t \mf{";"}\vdash \text{main}:T}
{}

#### program

Judgment: $\textit{prog}:T$

\logicRule
{
\varnothing,\varnothing, ls \vdash \Gamma,\Delta\quad
\Gamma,\mathit{mms}\vdash \text{main}:T\quad
\Gamma,\Delta\vdash e:T
}
{ls \ \mathit{mms} \ \mf{"main = "} \ e:T}
{}