### Inference Rules for Type Signatures

#### list-type-fields

Judgment: $\Gamma\vdash ltf:\{a_1:T_1,\dots,a_n:T_n\}$

\logicRule
{}
{\Gamma\vdash \mf{""}:\{\}}
{}

\logicRule
{\Gamma\vdash t : T_0\quad
\Gamma\vdash \mathit{ltf} : \{a_1:T_1,\dots,a_n:T_n\}\quad
\{a_0:T_0,a_1:T_1,\dots,a_n:T_n\}=T
}
{\Gamma\vdash a_0 \ \mf{":"} \ t \ \mf{","} \ \mathit{ltf}:T}
{}

The type context $\Gamma$ is used in the judgment $\Gamma\vdash t:T_0$ that turns the type signature $t$ into a type $T_0$.

#### list-type

Judgment: $\Gamma\vdash lt:(T_1,\dots,T_n)$

\logicRule
{}
{\Gamma\vdash \mf{""}:()}
{}

\logicRule
{\Gamma\vdash t:T_0\quad
\Gamma\vdash lt:(T_1,\dots,T_n)\quad
(T_0,T_1,\dots,T_n)=T
}
{\Gamma\vdash t \ lt:T}
{}

#### type

Judgment: $\Gamma\vdash t:T$

\logicRule
{\mathit{Bool} = T}
{\Gamma\vdash \mf{"Bool"}:T}
{}

\logicRule
{\mathit{Int} = T}
{\Gamma\vdash\mf{"Int"}:T}
{}

\logicRule
{\mathit{List} \ T_2 = T_1\quad
\Gamma\vdash t:T_2}
{\Gamma\vdash\mf{"List" t}:T_1}
{}

\logicRule
{(T_1,T_2) = T_0\quad
\Gamma\vdash t_1:T_1\quad
\Gamma\vdash t_2:T_2
}
{\Gamma\vdash\mf{"("} \ t_1 \ \mf{","} \ t_2 \ \mf{")"}:T_0}
{}

\logicRule
{\Gamma\vdash ltf:T}
{\Gamma\vdash\mf{"\{"} \ ltf \ \mf{"\}"}:T}
{}

\logicRule
{T_1 \to T_2 = T_0\quad
\Gamma\vdash t_1:T_1\quad
\Gamma\vdash t_2:T_2
}
{\Gamma\vdash t_1 \to t_2:T_0}
{}

\logicRule
{(c,T')\in\Gamma\quad
\Gamma\vdash l:(T_1,\dots,T_n)\quad
\overline{T'} \ T_1 \dots T_n = T
}
{\Gamma\vdash c \ l:T}
{}
For a given type $T$ we write the application constructor as $\overline{T}$.

\logicRule
{\forall a.a = T}
{\Gamma\vdash a:T}
{}

```{block2, type="myexample",latex.options="_"}
In example \ref{ex:reverse_list} we have looked at the syntax for a list reversing function.

The type signiture for the $\mf{reverse}$ function was $\mf{List a -> List a}$. We will now show how we can obtain the curresponding type $T_0$. For that, let $\Gamma = \varnothing$.
  
\begin{center}
\small
\begin{prooftree}
        \AxiomC{}
      \UnaryInfC{$\forall a.a=T_3$}
    \UnaryInfC{$\varnothing \vdash a:T_3$}
      \AxiomC{}
    \UnaryInfC{$List \ T_3=T_1$}
  \BinaryInfC{$\varnothing \vdash \mathit{List} a:T_1$}
        \AxiomC{}
      \UnaryInfC{$\forall a.a=T_4$}
    \UnaryInfC{$\varnothing \vdash a:T_4$}
      \AxiomC{}
    \UnaryInfC{$\mathit{List} \ T_4=T_2$}
  \BinaryInfC{$\varnothing \vdash \mathit{List} a:T_2$}
\BinaryInfC{$T_1 \to T_2 = T_0$}
\UnaryInfC{$\varnothing\vdash \mf{List a -> List a}:T_0$}
\end{prooftree}
\end{center}
```

We can therefore conclude that $T_0 = \mathit{List} \ (\forall a.a) \to \mathit{List} \ (\forall a.a)= \forall a. \mathit{List} \ a \to \mathit{List} \ a$.