\setcounter{section}{3}
\setcounter{subsection}{2}

## Type Inference

In the first section of this chapter we defined a type system, in the second section we introduced a syntax for our language. Now we want to define rules how to obtain the type of a given program written in our language.

### Typing Judgments

A type system is a set of inference rules to derive various kinds of typing judgments. These _inference rules_ have the following form

$$
\frac
{P_1 \dots P_n}
{C}
$$
where the judgments $P_1$ up to $P_n$ are the premises of the rule and the judgment $C$ is its conclusion.

We can read it in two ways:

* "If all premises hold then the conclusion holds as well" or
* "To prove the conclusion we need to prove all premises".

We will now provide a judgment for every production rule defined in the last section. Ultimately, we will have a judgment $p:T$ which indicates that a program $p$ is of a type $T$ and therefore well-formed.

If the type $T$ is known then we talk about _type checking_ else we call the process of finding the judgment _type inference_.

#### Type Signature Judgments

For type signature judgments, let $\Gamma$ be a type context, $T\in\mathcal{T}$ and $a_i\in\mathcal{V},T_i\in\mathcal{T}$ for all $i\in\mathbb{N}_1^n$ and $n\in\mathbb{N}$.

For $\mathit{ltf}\in\mf{<list-type-fields>}$ the judgment has the form
$$\Gamma\vdash \mathit{ltf}:\{a_1:T_1,\dots,a_n:T_n\}$$
which can be read as "given $\Gamma$, $ltf$ has the type $\{a_1:T_1,\dots,a_n:T_n\}$".

For $\mathit{lt}\in\mf{<list-type>}$ the judgment has the form
$$\Gamma\vdash \mathit{lt}:(T_1,\dots,T_n)$$
which can be read as "given $\Gamma$, $lt$ defines the list $(T_1,\dots,T_n)$".

For $t\in\mf{<type>}$ the judgment has the form
$$\Gamma\vdash t:T$$
which can be read as "given $\Gamma$, $t$ has the type $T$".

#### Expression Judgments

For expression judgments, let $\Gamma,\Delta$ be type contexts, $T\in\mathcal{T}$, $a\in\mathcal{V}$ and $T_i\in\mathcal{T},a_i\in\mathcal{V}$ for all $i\in\mathbb{N}_0^n,n\in\mathbb{N}$.

For $\mathit{lef}\in\mf{<list-exp-field>}$ the judgment has the form
$$\Gamma,\Delta\vdash \mathit{lef}:\{a_1:T_1,\dots, a_n:T_n\}$$
which can be read as "given $\Gamma$ and $\Delta$, $\mathit{lef}$ has the type $\{a_1:T_1,\dots,a_n:T_n\}$".

For $\mathit{mes}\in\mf{<maybe-exp-sign>}$ the judgment has the form
$$\Gamma,\mathit{mes}\vdash a:T$$
which can be read as "given $\Gamma$, $a$ has the type $T$ under the assumption $\mathit{mes}$".

For $b\in\mf{<bool>}$ the judgment has the form
$$b:T$$
which can be read as "$b$ has the type $T$".

For $i\in\mf{<int>}$ the judgment has the form
$$e:T$$
which can be read as "$i$ has the type $T$".

For $\mathit{le}\in\mf{<list-exp>}$ the judgment has the form
$$\Gamma,\Delta\vdash \mathit{le}:\mathit{List} \ T$$
which can be read as "given $\Gamma$ and $\Delta$, $le$ has the type $\mathit{List} \ T$".

For $e\in\mf{<exp>}$ the judgment has the form
$$\Gamma,\Delta\vdash e:T$$
which can be read as "given $\Gamma$ and $\Delta$, $e$ is of type $T$".

#### Statement Judgments

For statement judgments, let $\Gamma,\Gamma_1,\Gamma_2,\Delta,\Delta_1,\Delta_2$ be a type contexts, $T,T_1,T_2\in\mathcal{T}$, $a\in\mathcal{V}$ and $T_i,A_i\in\mathcal{T},a_i\in\mathcal{V}$ for $i\in\mathbb{N}_0^n$
and $T_{i,j}\in\mathcal{T}$ for $i\in\mathbb{N}_0^n,n\in\mathbb{N},j\in\mathbb{N}_0^{k_i}$ and $k_i\in\mathbb{N}$.

For $\mathit{lsv}\in\mf{<list-statement-var}$ the judgment has the form
$$\mathit{lsv}:(a_1,\dots,a_n)$$
which can be read as "$\mathit{lsv}$ describes the list $(a_1,\dots,a_n)$".

For $\mathit{ls}\in\mf{<list-statement>}$ the judgment has the form
$$\Gamma_1,\Delta_2,\mathit{ls}\vdash \Gamma_2,\Delta_2$$
which can be read as "the list of statements $\mathit{ls}$ maps $\Gamma_1$ to $\Gamma_2$ and $\Delta_1$ to $\Delta_2$".

For $\mathit{mss}\in\mf{<maybe-statement-sign>}$ the judgment has the form
$$\Gamma,\mathit{mss}\vdash a:T$$
which can be read as "given $\Gamma$, $a$ has the type $T_2$ under the assumption $\mathit{mss}$".

For $s\in\mf{<statement>}$ the judgment has the form
$$\Gamma_1,\Delta_1,s\vdash \Gamma_2,\Delta_2$$
which can be read as "the statement $s$ maps $\Gamma_1$ to $\Gamma_2$ and $\Delta_1$ to $\Delta_2$".

For $\mathit{mms}\in\mf{<maybe-main-sign>}$ the judgment has the form
$$\Gamma,\mathit{mms}\vdash \text{main}:T$$
which can be read as "the main function has type $T$ under the assumtion $\mathit{mms}$".

For $\textit{prog}\in\mf{<program>}$ the judgment has the form
$$\textit{prog}:T$$
which can be read as "the program $prog$ is wellformed and has the type $T$".

### Auxiliary Definitions

We will assume that $"T \text{ is a mono type}"$, $"T \text{ is a type variable}"$ and $T_1 = T_2$ denotes the equiality of two given types $T_1$ and $T_2$.

We will write ${a_1,\dots,a_n}=\text{free}(T)$ to denote all free variables $a_1,\dots,a_n$ of $T$.

#### Instantiation, Generalization

The type system that we are using is polymorphic, meaning that whenever a judgment holds for a type, it will also hold for a more specific type. To counter this polymorphism we will force the types in a judgment to be unique by explicitly stating whenever we want to use a more specific or general type.

```{definition,name="Instantiation"}
\begin{letIn}
$\Delta:\mathcal{V}\nrightarrow \mathcal{T}$ be a type context, $T\in\mathcal{T}$ and $e$ be an expression.
\end{letIn}

Then we define

$$
e \sqsubseteq_\Delta T :\Leftrightarrow \exists T_0\in\mathcal{T}. (e,T_0)\in\Delta \land T_0 \sqsubseteq T
$$

Note that $\Delta$ is a partial function and therefore $\Delta(e)$ would only be defined if $T_0$ exists. If $T_0$ does not exist, then this predicate will be false.
```

The act of replacing $T_0$ with the more specific type $T$ is called _Instantiation_ and is typically in the text books introduced as an additional inference rule.

```{definition,name="Most General Type"}
\begin{letIn} $\Gamma$ be a type context, $T\in\mathcal{T}$, . 
\end{letIn}

We define $\overline{\Gamma}:\Gamma \to \mathcal{T}$ as

\[\begin{aligned}
\overline{\Gamma}(T) := &\forall a_1 \dots \forall a_n.T_0\\
&\text{such that } \{a_1,\dots,a_n\}=\text{free}(T')\setminus \{a \ | \ (a,\_)\in\Gamma\}\\
& \text{where } a_i\in\mathcal{V} \text{ for } i\in\mathbb{N}_0^n \text{ and } T_0 \text{ is the mono type of } T.
\end{aligned}\]

We say $\overline{\Gamma}(T)$ is _the most general type_ of $T$.

```

The most general type ensures that all type variables are bound by either an quantifier or a type alias in the type context $\Gamma$. It also ensure that every type variable bound by a quantifier occures in the mono type $T_0$. The act of replacing types with more general onces, by binding free variables, is called _Generalization_ and is also typically found as an inference rule in text books.

#### Predefined Types

Additionally, we define

$$
\begin{aligned}
\mathit{Bool}&:=\mu \_.\mathit{True} | \mathit{False}\\
\mathit{Nat}&:=\mu C. 1 | \mathit{Succ} \ C\\
\mathit{Int}&:=\mu \_. 0 \ | \ \mathit{Pos} \ Nat \ | \ \mathit{Neg} \ \mathit{Nat}\\
\mathit{List}&:=\forall a.\mu C. [ \ ] \ | \mathit{Cons} \ a \ C
\end{aligned}
$$